# fastchat_t5:
#   tokenizer: t5-small
#   model: t5-small
#   type: seq2seq

dlite:
  tokenizer: aisquared/dlite-v2-1_5b
  model: aisquared/dlite-v2-1_5b
  type: causal

# securityllm:
#   tokenizer: ZySec-AI/SecurityLLM
#   model: ZySec-AI/SecurityLLM
#   type: causal

# llama3:
#   tokenizer: meta-llama/Llama-3.2-3B
#   model: meta-llama/Llama-3.2-3B
#   type: causal

# llama2:
#   tokenizer: meta-llama/Llama-2-7b-hf
#   model: meta-llama/Llama-2-7b-hf
#   type: causal

# gemma:
#   tokenizer: google/gemma-2-2b-it
#   model: google/gemma-2-2b-it
#   type: causal

