information_extraction:
  maet:
    dataset_path: datasets/SECURE/Dataset/SECURE - MAET.tsv
    input_column: Input
    expected_column: Expected
  cwet:
    dataset_path: datasets/SECURE/Dataset/SECURE - CWET.tsv
    input_column: Input
    expected_column: Expected

knowledge_understanding:
  kcv:
    dataset_path: datasets/SECURE/Dataset/SECURE - KCV.tsv
    input_column: Input
    expected_column: Expected
  vood:
    dataset_path: datasets/SECURE/Dataset/SECURE - VOOD.tsv
    input_column: Input
    expected_column: Expected

reasoning_and_problem_solving:
  rert:
    dataset_path: datasets/SECURE/Dataset/SECURE - RERT.tsv
    input_column: Input
    expected_column: Expected
  cpst:
    dataset_path: datasets/SECURE/Dataset/SECURE - CPST.tsv
    input_column: Input
    expected_column: Expected
